//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoProyectoWeb.Views.Home
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AhorcadoEntities : DbContext
    {
        public AhorcadoEntities()
            : base("name=AhorcadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Palabra> Palabra { get; set; }
        public virtual DbSet<Partida> Partida { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
