//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhorcadoProyectoWeb.Views.Home
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int IdPartida { get; set; }
        public int IdUsuario { get; set; }
        public int IdPalabra { get; set; }
        public byte Dificultad { get; set; }
        public System.DateTime FechaHora { get; set; }
        public bool Gano { get; set; }
        public int Puntos { get; set; }
    
        public virtual Palabra Palabra { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
